package com.splmeter.entities;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "MODE".
 */
public class Mode {

    private Integer mode_id;
    private String mode_code;
    private String mode_name_cn;
    private String mode_name_en;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public Mode() {
    }

    public Mode(Integer mode_id, String mode_code, String mode_name_cn, String mode_name_en) {
        this.mode_id = mode_id;
        this.mode_code = mode_code;
        this.mode_name_cn = mode_name_cn;
        this.mode_name_en = mode_name_en;
    }

    public Integer getMode_id() {
        return mode_id;
    }

    public void setMode_id(Integer mode_id) {
        this.mode_id = mode_id;
    }

    public String getMode_code() {
        return mode_code;
    }

    public void setMode_code(String mode_code) {
        this.mode_code = mode_code;
    }

    public String getMode_name_cn() {
        return mode_name_cn;
    }

    public void setMode_name_cn(String mode_name_cn) {
        this.mode_name_cn = mode_name_cn;
    }

    public String getMode_name_en() {
        return mode_name_en;
    }

    public void setMode_name_en(String mode_name_en) {
        this.mode_name_en = mode_name_en;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
