package com.splmeter.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.splmeter.entities.SoundSource;

import com.splmeter.dao.SoundSourceDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig soundSourceDaoConfig;

    private final SoundSourceDao soundSourceDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        soundSourceDaoConfig = daoConfigMap.get(SoundSourceDao.class).clone();
        soundSourceDaoConfig.initIdentityScope(type);

        soundSourceDao = new SoundSourceDao(soundSourceDaoConfig, this);

        registerDao(SoundSource.class, soundSourceDao);
    }
    
    public void clear() {
        soundSourceDaoConfig.getIdentityScope().clear();
    }

    public SoundSourceDao getSoundSourceDao() {
        return soundSourceDao;
    }

}
