package com.splmeter.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.splmeter.entities.SoundSource;
import com.splmeter.entities.Mode;
import com.splmeter.entities.AsmtValue;
import com.splmeter.entities.SPLValue;

import com.splmeter.dao.SoundSourceDao;
import com.splmeter.dao.ModeDao;
import com.splmeter.dao.AsmtValueDao;
import com.splmeter.dao.SPLValueDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig soundSourceDaoConfig;
    private final DaoConfig modeDaoConfig;
    private final DaoConfig asmtValueDaoConfig;
    private final DaoConfig sPLValueDaoConfig;

    private final SoundSourceDao soundSourceDao;
    private final ModeDao modeDao;
    private final AsmtValueDao asmtValueDao;
    private final SPLValueDao sPLValueDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        soundSourceDaoConfig = daoConfigMap.get(SoundSourceDao.class).clone();
        soundSourceDaoConfig.initIdentityScope(type);

        modeDaoConfig = daoConfigMap.get(ModeDao.class).clone();
        modeDaoConfig.initIdentityScope(type);

        asmtValueDaoConfig = daoConfigMap.get(AsmtValueDao.class).clone();
        asmtValueDaoConfig.initIdentityScope(type);

        sPLValueDaoConfig = daoConfigMap.get(SPLValueDao.class).clone();
        sPLValueDaoConfig.initIdentityScope(type);

        soundSourceDao = new SoundSourceDao(soundSourceDaoConfig, this);
        modeDao = new ModeDao(modeDaoConfig, this);
        asmtValueDao = new AsmtValueDao(asmtValueDaoConfig, this);
        sPLValueDao = new SPLValueDao(sPLValueDaoConfig, this);

        registerDao(SoundSource.class, soundSourceDao);
        registerDao(Mode.class, modeDao);
        registerDao(AsmtValue.class, asmtValueDao);
        registerDao(SPLValue.class, sPLValueDao);
    }
    
    public void clear() {
        soundSourceDaoConfig.getIdentityScope().clear();
        modeDaoConfig.getIdentityScope().clear();
        asmtValueDaoConfig.getIdentityScope().clear();
        sPLValueDaoConfig.getIdentityScope().clear();
    }

    public SoundSourceDao getSoundSourceDao() {
        return soundSourceDao;
    }

    public ModeDao getModeDao() {
        return modeDao;
    }

    public AsmtValueDao getAsmtValueDao() {
        return asmtValueDao;
    }

    public SPLValueDao getSPLValueDao() {
        return sPLValueDao;
    }

}
