package com.splmeter.jsonobject;

import com.splmeter.entities.SPLValue;
import com.splmeter.utils.DateTimeTools;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table "SPLVALUE".
 */
public class JsonSPLValue {

	private String time;
	private Integer earphone;
	private Float lng;
	private Float lat;
	private Float alt;
	private Float acc;
	private Float spl;
	private Float mainF;
	private Float maxLpa;
	private int asmt_id;

	// KEEP FIELDS - put your custom fields here
	// KEEP FIELDS END

	public JsonSPLValue() {
	}

	public JsonSPLValue(SPLValue splValue) {
		try {
			this.time = DateTimeTools.DateToStringForSecond(splValue.getTime());
			this.earphone = splValue.getEarphone();
			this.lng = splValue.getLng();
			this.lat = splValue.getLat();
			this.alt = splValue.getAlt();
			this.acc = splValue.getAcc();
			this.spl = splValue.getSpl();
			this.mainF = splValue.getMainF();
			this.maxLpa = splValue.getMaxLpa();
			this.asmt_id = Long.valueOf(splValue.getAsmt_id()).intValue();
		} catch (Exception e) {
			// TODO: handle exception
		}
	}

	public String getTime() {
		return time;
	}

	public void setTime(String time) {
		this.time = time;
	}

	public Integer getEarphone() {
		return earphone;
	}

	public void setEarphone(Integer earphone) {
		this.earphone = earphone;
	}

	public Float getLng() {
		return lng;
	}

	public void setLng(Float lng) {
		this.lng = lng;
	}

	public Float getLat() {
		return lat;
	}

	public void setLat(Float lat) {
		this.lat = lat;
	}

	public Float getAlt() {
		return alt;
	}

	public void setAlt(Float alt) {
		this.alt = alt;
	}

	public Float getAcc() {
		return acc;
	}

	public void setAcc(Float acc) {
		this.acc = acc;
	}

	public Float getSpl() {
		return spl;
	}

	public void setSpl(Float spl) {
		this.spl = spl;
	}

	public Float getMainF() {
		return mainF;
	}

	public void setMainF(Float mainF) {
		this.mainF = mainF;
	}

	public Float getMaxLpa() {
		return maxLpa;
	}

	public void setMaxLpa(Float maxLpa) {
		this.maxLpa = maxLpa;
	}

	public int getAsmt_id() {
		return asmt_id;
	}

	public void setAsmt_id(int asmt_id) {
		this.asmt_id = asmt_id;
	}

}
